### ISSUE TITLE
[Feature Request] Enable for workspace switch with touchpad gesture?

### ISSUE THREAD

**Issue by dlehmenk** [christopher-l/focus-follows-workspace#2]
Hey,

thanks for making this extension, it's super useful! :)

Right now it works as you write when switching workspaces using a keyboard shortcut. On my notebook though I mostly use the three finger touch gesture for switching and was wondering, if you could also include that?

**Comment by christopher-l** [comment]
Hi dlehmenk,

~~What features are you missing when switching workspaces via touchpad? I can think of the focus handling and skipping empty workspaces (when configured), or is there something else?~~
Sorry, I thought this feature request was for another extension.

**Comment by christopher-l** [comment]
@dlehmenk One other question though: I have another extension that includes the functionality of this one: https://github.com/christopher-l/space-bar
Would it make sense, to add support for handling focus when switching via touchpad to the "Space Bar" extension and have a mode to disable the UI elements completely to avoid code duplication or would you prefer to use this separate extension just for focus handling?

**Comment by dlehmenk** [comment]
Hi christopher-l,

sorry for the late reply. I didn't know about the space bar extension and am glad you mention it, because I missed that feature and now i have it back :smiley: But I don't quite understand what you mean with the same functionality. When I enable the space bar extension and disable this one, my focus still switches to the window on my secondary monitor, no matter if I switch by keyboard shortcut or touch gesture. So for the moment I have both enabled and would be happy if you include this in either of them :)

**Comment by christopher-l** [comment]
> When I enable the space bar extension and disable this one, my focus still switches to the window on my secondary monitor, no matter if I switch by keyboard shortcut or touch gesture. 

Ah, I didn't mention that this only works when using the keyboard shortcuts for switching workspaces by the Space Bar extension (and possibly disabling the ones by the system)

> I missed that feature and now i have it back

What feature is that, or just the whole thing?

**Comment by dlehmenk** [comment]
> What feature is that, or just the whole thing?

The whole extension :D


>> When I enable the space bar extension and disable this one, my focus still switches to the window on my secondary monitor, no matter if I switch by keyboard shortcut or touch gesture.

> Ah, I didn't mention that this only works when using the keyboard shortcuts for switching workspaces by the Space Bar extension (and possibly disabling the ones by the system)

Ah you mean the Super + 1..n for example! Yeah, that works for me, too. But if I see it correctly it has no shortcuts for move one workspace up/down, which is what I use most (if not the touchpad).

**Comment by christopher-l** [comment]
Ah, I see! I don't know when I'll get round to this, but at least I understand your use case now. Thanks for clarifying!

**Comment by christopher-l** [comment]
@dlehmenk Could you check if this branch works for you? https://github.com/christopher-l/focus-follows-workspace/tree/feat/touch-gesture

```sh
git clone https://github.com/christopher-l/focus-follows-workspace.git -b feat/touch-gesture
cd focus-follows-workspace/
./bundle.sh -i
```
Then log out and log in again.

**Comment by dlehmenk** [comment]
Yes it does! Thank you for implementing it and also so soon 🙂

**Comment by christopher-l** [comment]
:+1:
