### ISSUE TITLE
Please support Gnome Shell 44

### ISSUE THREAD

**Issue by towolf** [christopher-l/focus-follows-workspace#3]
The extension stopped working after I upgraded to Fedora 38 and it immediately messed up my workflow.

![image](https://user-images.githubusercontent.com/345210/234019941-13d1823c-d858-4ee3-ad2c-5f4457bb0415.png)

**Comment by christopher-l** [comment]
Hi @towolf,

Thanks for the report! I haven't tested Gnome 44 yet. Could you check if this works?

[focus-follows-workspace@christopher.luebbemeier.gmail.com.shell-extension.zip](https://github.com/christopher-l/focus-follows-workspace/files/11311471/focus-follows-workspace%40christopher.luebbemeier.gmail.com.shell-extension.zip)

```sh
gnome-extensions install --force focus-follows-workspace@christopher.luebbemeier.gmail.com.shell-extension.zip
```

**Comment by towolf** [comment]
Seems to work fine. Had to reboot because GS under Wayland does not allow reloading on the fly.

**Comment by schuhumi** [comment]
It works fine for me as well! 🙂 (after logout+login on wayland)

**Comment by christopher-l** [comment]
Perfect, thanks for testing!

I submitted the updated version.
