### ISSUE TITLE
Relocating mouse pointer

### ISSUE THREAD

**Issue by cachapa** [christopher-l/focus-follows-workspace#4]
I really like this extension, but it seems to have the side effect of relocating my mouse pointer to the middle of active workspace after switching.

Not sure if it's by design or a side-effect of changing the workspace focus, but I find it very confusing behavior.

Fedora 38
Gnome 44.1
Wayland

**Comment by christopher-l** [comment]
Hi, thanks for your report!
That is a side effect of a behavior that should focus an application on the switched-to workspace and should only occur when the cursor is on a secondary screen.
I wasn't aware that this caused confusion. ~~I'll consider adding an option to disable the behavior.~~

Edit: I confused the project. It might be needed to move the pointer to the primary screen to be able to focus the right window. Does this also happen for you, when the pointer is already on the primary screen?

**Comment by jgato** [comment]
Hi,
first of all awesome!! this is saving me a lot of time. I cannot believe something like that as the main behaviour.
But also I suffer the same explained here. 
If my focus is not in the primary window, why dont to keep the focus and pointer there when I switch to another workspace?.
If my focus is in the primary window, the way this extension is acting is just perfect.
Is it possible to solve (or making an option) the explained above?

**Comment by cachapa** [comment]
@christopher-l sorry I missed your update. You're right that it doesn't move the mouse when it's already on the primary screen.

**Comment by christopher-l** [comment]
Ok, it's working as expected than. I'll look into how I could provide the basic functionality without moving the cursor when I find the time.

**Comment by christopher-l** [comment]
It turns out, I could not reproduce the original case where moving the cursor to the primary screen was necessary for the extension to work. Probably that was the side effect of some other extension I was using at the time.

I uploaded a version with an option to move the cursor in case someone prefers the old behavior. Could you guys test if this works for you?

[focus-follows-workspace@christopher.luebbemeier.gmail.com.shell-extension.zip](https://github.com/christopher-l/focus-follows-workspace/files/11472006/focus-follows-workspace%40christopher.luebbemeier.gmail.com.shell-extension.zip)

**Comment by jgato** [comment]
sorry @christopher-l , what is exactly the new change?

**Comment by christopher-l** [comment]
When installing the zip file uploaded above using
```sh
gnome-extensions install --force focus-follows-workspace@christopher.luebbemeier.gmail.com.shell-extension.zip
```

and logging out and back in, you should have a version that does not move the cursor anymore (unless if enabled in the extensions preferences).

**Comment by jgato** [comment]
works perfectly @christopher-l , thanks

**Comment by christopher-l** [comment]
Thanks for testing!

I submitted the update.
