### ISSUE TITLE
Stopped working in Gnome 45.0

### ISSUE THREAD

**Issue by towolf** [christopher-l/focus-follows-workspace#7]
I use this extension in my multi-monitor setup, and of course something broke it again after a recent system upgrade.

**Comment by Vyogami** [comment]
any update on this?

**Comment by christopher-l** [comment]
I submitted a migrated version for review. Should hit extensions.gnome.org once accepted.

**Comment by danielquinn-uw** [comment]
My system auto-updated this morning and it appears to be working now, thanks!
